#!/bin/bash
#SBATCH -p gpu_short
bash $HOME/miniconda3/etc/profile.d/conda.sh
source activate pytorch11
python file_generator.py --image-dir=./images/ --destination-dir=/lustre2/0/wsdarts/datasets/test/
source deactivate