#!/bin/bash
#SBATCH -p gpu
#SBATCH -t 100:00:00
bash $HOME/miniconda3/etc/profile.d/conda.sh
source activate pytorch11
source deactivate
python file_generator.py --image-dir=/scratch/nodespecific/int1/mhouben/CASIA_aligned/val/ --destination-dir=/lustre2/0/wsdarts/datasets/CASIA_aligned_split_correctly/val/