#!/bin/bash
#SBATCH -p gpu
#SBATCH -t 100:00:00
bash $HOME/miniconda3/etc/profile.d/conda.sh
source activate pytorch11
python file_generator.py --image-dir=/lustre2/0/wsdarts/jpg_datasets/lfw/ --destination-dir=/lustre2/0/wsdarts/datasets/lfw/
source deactivate